"""add_market_signals_table

Revision ID: 2296ee2836cf
Revises: 6be9695856dc
Create Date: 2026-03-24 13:54:31.378160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2296ee2836cf'
down_revision: Union[str, Sequence[str], None] = '6be9695856dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_type', 'key', 'recorded_at', name='uix_market_signals_type_key_date')
    )
    op.create_index('ix_market_signals_type_key_date', 'market_signals', ['signal_type', 'key', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_signals_type_key_date', table_name='market_signals')
    op.drop_table('market_signals')
    # ### end Alembic commands ###
