"""add_model_versions_table

Revision ID: 96b721eec1c9
Revises: a7c615ddafa7
Create Date: 2026-03-24 15:04:14.301190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b721eec1c9'
down_revision: Union[str, Sequence[str], None] = 'a7c615ddafa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mape', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_model_versions_active', 'model_versions', ['user_id', 'product_id'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_model_versions_active', table_name='model_versions', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = true'))
    op.drop_table('model_versions')
    # ### end Alembic commands ###
